const movie = [
		{
			"movie_id" : 1,
			"title" : "Iron Man",
			"poster": "https://www.vintagemovieposters.co.uk/wp-content/uploads/2019/04/IMG_8468.jpeg",
			"phase" : "Phase One: Avengers Assembled",
			"category_name" : "Action",
			"release_year" : 2015,
			"running_time" : 126,
			"rating_name" : "PG-13",
			"disc_format_name" : "Blu-ray",
			"number_discs" : 1,
			"viewing_format_name" : "Widescreen",
			"aspect_ratio_name" : "2.35:1",
			"status" : 1,
			"release_date" : "May 2, 2008",
			"budget" : "140,000,000",
			"gross" : "318,298,180",
			"time_stamp" : "2015-05-03"
		},
        {
			"movie_id" : 2,
			"title" : "The Incredible Hulk",
			"poster": "https://picfiles.alphacoders.com/351/351486.jpg",
			"phase" : "Phase One: Avengers Assembled",
			"category_name" : "Action",
			"release_year" : 2008,
			"running_time" : 112,
			"rating_name" : "PG-13",
			"disc_format_name" : "DVD",
			"number_discs" : 3,
			"viewing_format_name" : "Widescreen",
			"aspect_ratio_name" : "2.35:1",
			"status" : 1,
			"release_date" : "June 13, 2008",
			"budget" : "150,000,000",
			"gross" : "134,518,390",
			"time_stamp" : "2008-10-21"
		},
        {
			"movie_id" : 3,
			"title" : "Iron Man 2",
			"poster": "https://image.tmdb.org/t/p/original/5tCA3oZXLRPHmS5DIDnlu7hY4Ab.jpg",
			"phase" : "Phase One: Avengers Assembled",
			"category_name" : "Action",
			"release_year" : 2015,
			"running_time" : 124,
			"rating_name" : "PG-13",
			"disc_format_name" : "Blu-ray",
			"number_discs" : 1,
			"viewing_format_name" : "Widescreen",
			"aspect_ratio_name" : "2.35:1",
			"status" : 1,
			"release_date" : "May 7, 2010",
			"budget" : "200,000,000",
			"gross" : "312,057,433",
			"time_stamp" : "2015-05-03"
		},
        {
			"movie_id" : 4,
			"title" : "Thor",
			"poster": "https://image.tmdb.org/t/p/original/prSfAi1xGrhLQNxVSUFh61xQ4Qy.jpg",
			"phase" : "Phase One: Avengers Assembled",
			"category_name" : "Action",
			"release_year" : 2011,
			"running_time" : 115,
			"rating_name" : "PG-13",
			"disc_format_name" : "Blu-ray + DVD",
			"number_discs" : 2,
			"viewing_format_name" : "Widescreen",
			"aspect_ratio_name" : "2.35:1",
			"status" : 1,
			"release_date" : "May 6, 2011",
			"budget" : "150,000,000",
			"gross" : "181,015,141",
			"time_stamp" : "2011-10-30"
		},
        {
			"movie_id" : 5,
			"title" : "Captain America",
			"poster": "http://1.bp.blogspot.com/-3seW8l1Uw-w/Ti9mlTKu5tI/AAAAAAAABaM/KPFsQfZisXk/s1600/captain-america-movie-poster.jpg",
			"phase" : "Phase One: Avengers Assembled",
			"category_name" : "Action",
			"release_year" : 2011,
			"running_time" : 124,
			"rating_name" : "PG-13",
			"disc_format_name" : "Blu-ray + DVD",
			"number_discs" : 2,
			"viewing_format_name" : "Widescreen",
			"aspect_ratio_name" : "2.35:1",
			"status" : 1,
			"release_date" : "July 22, 2011",
			"budget" : "140,000,000",
			"gross" : "176,636,816",
			"time_stamp" : "2011-10-30"
		},
        {
			"movie_id" : 6,
			"title" : "Avengers",
			"poster": "https://image.tmdb.org/t/p/original/mhc5CvIZBN08cytjaZMbncw4v5u.jpg",
			"phase" : "Phase One: Avengers Assembled",
			"category_name" : "Science Fiction",
			"release_year" : 2012,
			"running_time" : 143,
			"rating_name" : "PG-13",
			"disc_format_name" : "Blu-ray + DVD",
			"number_discs" : 2,
			"viewing_format_name" : "Widescreen",
			"aspect_ratio_name" : "1.85:1",
			"status" : 1,
			"release_date" : "May 4, 2012",
			"budget" : "220,000,000",
			"gross" : "623,279,547",
			"time_stamp" : "2012-10-20"
		},
        {
			"movie_id" : 7,
			"title" : "Iron Man 3",
			"poster": "https://image.tmdb.org/t/p/original/bYWwiNJC8cEIJ32EBXjjWVhUZDI.jpg",
			"phase" : "Phase Two",
			"category_name" : "Action",
			"release_year" : 2015,
			"running_time" : 130,
			"rating_name" : "PG-13",
			"disc_format_name" : "Blu-ray + DVD",
			"number_discs" : 2,
			"viewing_format_name" : "Widescreen",
			"aspect_ratio_name" : "2.35:1",
			"status" : 1,
			"release_date" : "May 3, 2013",
			"budget" : "200,000,000",
			"gross" : "408,992,272",
			"time_stamp" : "2015-05-03"
		},
        {
			"movie_id" : 8,
			"title" : "Thor: The Dark World",
			"poster": "https://www.themoviedb.org/t/p/original/669Td9253rcXdtKmWdESIiaaW7E.jpg",
			"phase" : "Phase Two",
			"category_name" : "Science Fiction",
			"release_year" : 2013,
			"running_time" : 112,
			"rating_name" : "PG-13",
			"disc_format_name" : "Blu-ray",
			"number_discs" : 2,
			"viewing_format_name" : "Widescreen",
			"aspect_ratio_name" : "2.35:1",
			"status" : 1,
			"release_date" : "November 8, 2013",
			"budget" : "170,000,000",
			"gross" : "206,360,018",
			"time_stamp" : "2014-03-04"
		},
        {
			"movie_id" : 9,
			"title" : "Captain America: The Winter Soldier",
			"poster": "https://www.themoviedb.org/t/p/original/lStArqSSJvoiWJAW1lEV2MI925k.jpg",
			"phase" : "Phase Two",
			"edition" : "Blu-ray Edition",
			"release_year" : 2014,
			"running_time" : 136,
			"rating_name" : "PG-13",
			"disc_format_name" : "Blu-ray",
			"number_discs" : 1,
			"viewing_format_name" : "Widescreen",
			"aspect_ratio_name" : "2.35:1",
			"status" : 1,
			"release_date" : "April 4, 2014",
			"budget" : "170,000,000",
			"gross" : "259,746,958",
			"time_stamp" : "2014-09-19"
		},
        {
			"movie_id" : 10,
			"title" : "Guardians of the Galaxy",
			"poster": "https://image.tmdb.org/t/p/original/vixT8D1nLAU9FNtLFC3zoY4siBM.jpg",
			"phase" : "Phase Two",
			"category_name" : "Science Fiction",
			"release_year" : 2014,
			"running_time" : 121,
			"rating_name" : "PG-13",
			"disc_format_name" : "Blu-ray",
			"number_discs" : 1,
			"viewing_format_name" : "Widescreen",
			"aspect_ratio_name" : "2.35:1",
			"status" : 1,
			"release_date" : "August 1, 2014",
			"budget" : "170,000,000",
			"gross" : "333,130,696",
			"time_stamp" : "2014-12-07"
		},
        {
			"movie_id" : 11,
			"title" : "Avengers: Age of Ultron",
			"poster": "https://www.themoviedb.org/t/p/original/tTzs0sigsjYotvnlSz2FYq0tx6M.jpg",
			"phase" : "Phase Two",
			"category_name" : "Science Fiction",
			"release_year" : 2015,
			"running_time" : 141,
			"rating_name" : "PG-13",
			"disc_format_name" : "Blu-ray",
			"number_discs" : 1,
			"viewing_format_name" : "Widescreen",
			"aspect_ratio_name" : "2.35:1",
			"status" : 1,
			"release_date" : "May 1, 2015",
			"budget" : "250,000,000",
			"gross" : "458,991,599",
			"time_stamp" : "2015-12-07"
		},
        {
			"movie_id" : 12,
			"title" : "Ant-Man",
			"poster": "https://is1-ssl.mzstatic.com/image/thumb/Video118/v4/e7/7d/65/e77d6558-d597-5a93-f616-230881efcd2d/source/900x900bb.jpg",
			"phase" : "Phase Two",
			"category_name" : "Science Fiction",
			"release_year" : 2015,
			"running_time" : 132,
			"rating_name" : "PG-13",
			"disc_format_name" : "Blu-ray",
			"number_discs" : 1,
			"viewing_format_name" : "Widescreen",
			"aspect_ratio_name" : "1.85:1",
			"status" : 1,
			"release_date" : "July 17, 2015",
			"budget" : "130,000,000",
			"gross" : "179,017,481",
			"time_stamp" : "2015-12-07"
		},
        {
			"movie_id" : 13,
			"title" : "Captain America: Civil War",
			"poster": "https://1.bp.blogspot.com/-yMLpsYY5FGk/Vy0OZLozu2I/AAAAAAABNUQ/aGTBZZYoYFUH69wFyw-3L8Gebc4DrwFwQCLcB/s1600/captain-america-civil-war-poster.jpg",
			"phase" : "Phase Three",
			"category_name" : "Science Fiction",
			"release_year" : 2016,
			"running_time" : 147,
			"rating_name" : "PG-13",
			"disc_format_name" : "Blu-ray",
			"number_discs" : 1,
			"viewing_format_name" : "Widescreen",
			"aspect_ratio_name" : "2.39:1",
			"status" : 1,
			"release_date" : "May 6, 2016",
			"budget" : "250,00,000",
			"gross" : "408,084,349",
			"time_stamp" : "2017-11-09"
		},
        {
			"movie_id" : 14,
			"title" : "Doctor Strange",
			"poster": "http://brandnewcool.com/wp-content/uploads/2016/04/Doctor-Strange-Official-Poster-691x1024.jpg",
			"phase" : "Phase Three",
			"category_name" : "Science Fiction",
			"release_year" : 2016,
			"running_time" : 115,
			"rating_name" : "PG-13",
			"disc_format_name" : "Blu-ray",
			"number_discs" : 1,
			"viewing_format_name" : "Widescreen",
			"aspect_ratio_name" : "2.39:1",
			"status" : 1,
			"release_date" : "November 4, 2016",
			"budget" : "165,000,000",
			"gross" : "232,641,920",
			"time_stamp" : "2017-11-09"
		},
        {
			"movie_id" : 15,
			"title" : "Guardians of the Galaxy Vol. 2",
			"poster": "https://image.tmdb.org/t/p/original/lGjmEgZFXiTIZVQv1TJkty4mXR2.jpg",
			"phase" : "Phase Three",
			"category_name" : "Science Fiction",
			"release_year" : 2017,
			"running_time" : 136,
			"rating_name" : "PG-13",
			"disc_format_name" : "Blu-ray",
			"number_discs" : 1,
			"viewing_format_name" : "Widescreen",
			"aspect_ratio_name" : "2.39:1",
			"status" : 1,
			"release_date" : "May 5, 2017",
			"budget" : "200,000,000",
			"gross" : "389,213,281",
			"time_stamp" : "2017-11-09"
		},
        {
			"movie_id" : 16,
			"title" : "Spider-Man: Homecoming",
			"poster": "https://cdn.traileraddict.com/content/columbia-pictures/spiderman-homecoming-poster-3.jpg",
			"phase" : "Phase Three",
			"category_name" : "Science Fiction",
			"release_year" : 2017,
			"running_time" : 133,
			"rating_name" : "PG-13",
			"disc_format_name" : "Blu-ray",
			"number_discs" : 1,
			"viewing_format_name" : "Widescreen",
			"aspect_ratio_name" : "2.35:1",
			"status" : 1,
			"release_date" : "July 7, 2017",
			"budget" : "175,000,000",
			"gross" : "314,057,748",
			"time_stamp" : "2017-11-09"
		},
        {
			"movie_id" : 17,
			"title" : "Thor: Ragnarok",
			"poster": "https://www.themoviedb.org/t/p/original/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg",
			"phase" : "Phase Three",
			"category_name" : "Science Fiction",
			"release_year" : 2017,
			"running_time" : 130,
			"rating_name" : "PG-13",
			"disc_format_name" : "Blu-ray",
			"number_discs" : 1,
			"viewing_format_name" : "Widescreen",
			"aspect_ratio_name" : "2.35:1",
			"status" : 1,
			"release_date" : "November 3, 2017",
			"budget" : "180,000,000",
			"gross" : "tbd",
			"time_stamp" : "2017-11-09"
		},
        {
			"movie_id" : 18,
			"title" : "Black Panther",
			"poster": "https://image.tmdb.org/t/p/original/qLrKYbJVZnkqvHlSVe8HPIxSKvb.jpg",
			"phase" : "Phase Three",
			"category_name" : "Science Fiction",
			"release_year" : 2018,
			"running_time" : 0,
			"rating_name" : "PG-13",
			"disc_format_name" : "Blu-ray",
			"number_discs" : 1,
			"viewing_format_name" : "Widescreen",
			"aspect_ratio_name" : "2.39:1",
			"status" : 1,
			"release_date" : "February 16, 2018",
			"budget" : "tbd",
			"gross" : "tbd",
			"time_stamp" : "2018-01-09"
		},
        {
			"movie_id" : 19,
			"title" : "Avengers: Infinity War",
			"poster": "https://tse2.mm.bing.net/th?id=OIP.1jdklJKgjAe81COtBdjG9AHaLH&pid=Api&P=0&h=180",
			"phase" : "Phase Three",
			"category_name" : "Science Fiction",
			"release_year" : 2018,
			"running_time" : 0,
			"rating_name" : "PG-13",
			"disc_format_name" : "Blu-ray",
			"number_discs" : 1,
			"viewing_format_name" : "Widescreen",
			"aspect_ratio_name" : "2.39:1",
			"status" : 1,
			"release_date" : "May 4, 2018",
			"budget" : "tbd",
			"gross" : "tbd",
			"time_stamp" : "2018-01-09"
		},
        {
			"movie_id" : 20,
			"title" : "Ant-Man and the Wasp",
			"poster": "https://www.themoviedb.org/t/p/original/bUKxBMRXP4ymfmDAtQ4m2FVhbrW.jpg",
			"phase" : "Phase Three",
			"category_name" : "Science Fiction",
			"release_year" : 2018,
			"running_time" : 0,
			"rating_name" : "PG-13",
			"disc_format_name" : "Blu-ray",
			"number_discs" : 1,
			"viewing_format_name" : "Widescreen",
			"aspect_ratio_name" : "2.39:1",
			"status" : 1,
			"release_date" : "July 6, 2018",
			"budget" : "tbd",
			"gross" : "tbd",
			"time_stamp" : "2018-01-09"
		},
			{
				"movie_id" : 21,
				"title" : "Akira",
				"poster": "https://image.tmdb.org/t/p/original/av41os4M7c2Gneb1kkRUyTqdJJi.jpg",
				"category_name" : "Science Fiction",
				"edition" : "Signature Series",
				"release_year" : 1987,
				"running_time" : 124,
				"rating_name" : "R",
				"disc_format_name" : "DVD",
				"number_discs" : 1,
				"viewing_format_name" : "Widescreen",
				"aspect_ratio_name" : " 1.78:1",
				"status" : 1,
				"time_stamp" : "2006-01-02"
			},
			{
				"movie_id" : 22,
				"title" : "Alien",
				"poster": "https://www.themoviedb.org/t/p/original/ih64em743HBjcYIJXXZ5fZu4Qr1.jpg",
				"category_name" : "Science Fiction",
				"edition" : "Blu-ray Quadrilogy Edition",
				"release_year" : 1979,
				"running_time" : 116,
				"rating_name" : "R",
				"disc_format_name" : "Blu-ray",
				"number_discs" : 1,
				"viewing_format_name" : "Widescreen",
				"aspect_ratio_name" : " 2.35:1",
				"status" : 1,
				"time_stamp" : "2015-09-19"
			},
			{
				"movie_id" : 23,
				"title" : "Aliens",
				"poster": "https://image.tmdb.org/t/p/original/7lh0lceTCEatJlsmiwkun5AC4OV.jpg",
				"category_name" : "Science Fiction",
				"edition" : "Blu-ray Quadrilogy Edition",
				"release_year" : 1986,
				"running_time" : 137,
				"rating_name" : "R",
				"disc_format_name" : "Blu-ray",
				"number_discs" : 1,
				"viewing_format_name" : "Widescreen",
				"aspect_ratio_name" : " 1.85:1",
				"status" : 1,
				"time_stamp" : "2015-09-19"
			},
			{
				"movie_id" : 24,
				"title" : "Avatar",
				"poster": "https://image.tmdb.org/t/p/original/8Y7WrRK1iQHEX7UIftBeBMjPjWD.jpg",
				"category_name" : "Science Fiction",
				"edition" : "Extended Blu-Ray Collector Edition",
				"release_year" : 2009,
				"running_time" : 178,
				"rating_name" : "PG-13",
				"disc_format_name" : "Blu-ray",
				"number_discs" : 3,
				"viewing_format_name" : "Widescreen",
				"aspect_ratio_name" : " 1.78:1",
				"status" : 1,
				"time_stamp" : "2011-02-25"
			},
			{
				"movie_id" : 25,
				"title" : "Blade Runner",
				"poster": "https://static.rogerebert.com/uploads/movie/movie_poster/blade-runner-directors-cut-1992/large_p64TtbZGCElxQHpAMWmDHkWJlH2.jpg",
				"category_name" : "Science Fiction",
				"edition" : "30th Anniversary Collectors Edition",
				"release_year" : 1992,
				"running_time" : 117,
				"rating_name" : "R",
				"disc_format_name" : "Blu-ray",
				"number_discs" : 3,
				"viewing_format_name" : "Widescreen",
				"aspect_ratio_name" : " 2.78:1",
				"status" : 1,
				"time_stamp" : "2012-10-25"
			},
			{
				"movie_id" : 26,
				"title" : "Chappie",
				"poster": "https://www.themoviedb.org/t/p/original/6tgSZfqMPMu3EDeefa24eTNrX4O.jpg",
				"category_name" : "Science Fiction",
				"edition" : "Blu-ray Edition",
				"release_year" : 2015,
				"running_time" : 120,
				"rating_name" : "R",
				"disc_format_name" : "Blu-ray",
				"number_discs" : 1,
				"viewing_format_name" : "Widescreen",
				"aspect_ratio_name" : " 2.40:1",
				"status" : 1,
				"time_stamp" : "2015-07-19"
			},
			{
				"movie_id" : 27,
				"title" : "Children of Men",
				"poster": "https://i.pinimg.com/originals/b2/e2/eb/b2e2eb1cf75ee0afcacc15f55021c34e.jpg",
				"category_name" : "Science Fiction",
				"edition" : "Widescreen Edition",
				"release_year" : 2007,
				"running_time" : 110,
				"rating_name" : "R",
				"disc_format_name" : "DVD",
				"number_discs" : 10,
				"viewing_format_name" : "Widescreen",
				"aspect_ratio_name" : " 1.85:1",
				"status" : 1,
				"time_stamp" : "2007-05-07"
			},
			{
				"movie_id" : 28,
				"title" : "Cloud Atlas",
				"poster": "https://i.pinimg.com/originals/ea/a0/28/eaa028ee3fd68d9729a7cb92faa8410f.jpg",
				"category_name" : "Science Fiction",
				"edition" : "Blu-ray + DVD Edition",
				"release_year" : 2013,
				"running_time" : 172,
				"rating_name" : "R",
				"disc_format_name" : "Blu-ray + DVD",
				"number_discs" : 1,
				"viewing_format_name" : "Widescreen",
				"aspect_ratio_name" : " 1.78:1",
				"status" : 1,
				"time_stamp" : "2014-04-28"
			},
			{
				"movie_id" : 29,
				"title" : "Dark City",
				"poster": "https://alchetron.com/cdn/Dark-City-1998-film-images-107269b7-232d-4da7-84e9-f98363b2106.jpg",
				"category_name" : "Science Fiction",
				"edition" : "New Line Platinum Series",
				"release_year" : 1998,
				"running_time" : 96,
				"rating_name" : "R",
				"disc_format_name" : "DVD",
				"number_discs" : 1,
				"viewing_format_name" : "Widescreen",
				"aspect_ratio_name" : " 1.78:1",
				"status" : 1,
				"time_stamp" : "2006-01-02"
			},
			{
				"movie_id" : 30,
				"title" : "Dawn of the Planet of the Apes",
				"poster": "https://www.themoviedb.org/t/p/original/nIcZlG4DuAinlEkUzSIEmXy3F5v.jpg",
				"category_name" : "Science Fiction",
				"edition" : "Blu-ray + Digital HD",
				"release_year" : 2014,
				"running_time" : 130,
				"rating_name" : "PG-13",
				"disc_format_name" : "Blu-ray",
				"number_discs" : 1,
				"viewing_format_name" : "Widescreen",
				"aspect_ratio_name" : " 1.85:1",
				"status" : 1,
				"time_stamp" : "2014-12-07"
			},
			{
				"movie_id" : 31,
				"title" : "District 9",
				"poster": "https://img.moviesrankings.com/t/p/w1280/41uEqmmU6JMI2kpPlGrLe1iLggg.jpg",
				"category_name" : "Science Fiction",
				"edition" : "Widescreen Edition",
				"release_year" : 2009,
				"running_time" : 112,
				"rating_name" : "R",
				"disc_format_name" : "DVD",
				"number_discs" : 1,
				"viewing_format_name" : "Widescreen",
				"aspect_ratio_name" : " 1.85:1",
				"status" : 1,
				"time_stamp" : "2010-01-02"
			},
			{
				"movie_id" : 32,
				"title" : "Dredd",
				"poster": "https://www.themoviedb.org/t/p/original/9lLsDY2CI8a8d2Ej4F5t6XSR3iw.jpg",
				"category_name" : "Science Fiction",
				"edition" : "Blu-ray 3D",
				"release_year" : 2013,
				"running_time" : 95,
				"rating_name" : "R",
				"disc_format_name" : "Blu-ray",
				"number_discs" : 1,
				"viewing_format_name" : "Widescreen",
				"aspect_ratio_name" : " 1.85:1",
				"status" : 1,
				"time_stamp" : "2013-08-01"
			},
			{
				"movie_id" : 33,
				"title" : "Elysium",
				"poster": "https://image.tmdb.org/t/p/original/olNCKCnccHKfy41tgxCArB6zmit.jpg",
				"category_name" : "Science Fiction",
				"edition" : "Blu-Ray + DVD + Digital HD Combo Set",
				"release_year" : 2013,
				"running_time" : 109,
				"rating_name" : "R",
				"disc_format_name" : "Blu-ray + DVD",
				"number_discs" : 2,
				"viewing_format_name" : "Widescreen",
				"aspect_ratio_name" : " 2.40:1",
				"status" : 1,
				"time_stamp" : "2014-01-03"
			},
			{
				"movie_id" : 34,
				"title" : "Fifth Element",
				"poster": "https://picfiles.alphacoders.com/350/350080.jpg",
				"category_name" : "Science Fiction",
				"edition" : "Blu-ray Edition",
				"release_year" : 2007,
				"running_time" : 126,
				"rating_name" : "PG-13",
				"disc_format_name" : "Blu-ray",
				"number_discs" : 1,
				"viewing_format_name" : "Widescreen",
				"aspect_ratio_name" : " 2.40:1",
				"status" : 1,
				"time_stamp" : "2013-08-01"
			},
			{
				"movie_id" : 35,
				"title" : "Interstellar",
				"poster": "https://tse2.mm.bing.net/th?id=OIP.8A707ygGKj_-MsgM-gOchgHaKe&pid=Api&P=0&h=180",
				"category_name" : "Science Fiction",
				"edition" : "Blu-ray + DVD + Digital HD",
				"release_year" : 2015,
				"running_time" : 169,
				"rating_name" : "PG-13",
				"disc_format_name" : "Blu-ray + DVD",
				"number_discs" : 2,
				"viewing_format_name" : "Widescreen",
				"aspect_ratio_name" : " 2.35:1",
				"status" : 1,
				"time_stamp" : "2015-04-02"
			},
			{
				"movie_id" : 36,
				"title" : "Jurassic Park",
				"poster": "http://thefilmstage.com/wp-content/uploads/2014/08/jurassic_park_25.jpg",
				"category_name" : "Science Fiction",
				"edition" : "Blu-ray + DVD Edition",
				"release_year" : 2014,
				"running_time" : 127,
				"rating_name" : "PG-13",
				"disc_format_name" : "Blu-ray + DVD",
				"number_discs" : 2,
				"viewing_format_name" : "Widescreen",
				"aspect_ratio_name" : " 1.85:1",
				"status" : 1,
				"time_stamp" : "2014-10-05"
			},
			{
				"movie_id" : 37,
				"title" : "Looper",
				"poster": "https://100-movie.com/wp-content/uploads/2020/03/Looper.jpg",
				"category_name" : "Science Fiction",
				"edition" : "",
				"release_year" : 2012,
				"running_time" : 119,
				"rating_name" : "R",
				"disc_format_name" : "Blu-ray",
				"number_discs" : 1,
				"viewing_format_name" : "Widescreen",
				"aspect_ratio_name" : " 2.35:1",
				"status" : 1,
				"time_stamp" : "2013-01-04"
			},
			{
				"movie_id" : 38,
				"title" : "Matrix",
				"poster": "https://image.tmdb.org/t/p/original/dXNAPwY7VrqMAo51EKhhCJfaGb5.jpg",
				"category_name" : "Science Fiction",
				"edition" : "",
				"release_year" : 1999,
				"running_time" : 136,
				"rating_name" : "R",
				"disc_format_name" : "DVD",
				"number_discs" : 1,
				"viewing_format_name" : "Widescreen",
				"aspect_ratio_name" : " 1.85:1",
				"status" : 1,
				"time_stamp" : "2006-01-07"
			},
			{
				"movie_id" : 39,
				"title" : "Minority Report",
				"poster": "https://www.themoviedb.org/t/p/original/AkvtzsvH4yFOH99dVPJmDs28Gtt.jpg",
				"category_name" : "Science Fiction",
				"edition" : "",
				"release_year" : 2002,
				"running_time" : 146,
				"rating_name" : "PG-13",
				"disc_format_name" : "DVD",
				"number_discs" : 2,
				"viewing_format_name" : "Widescreen",
				"aspect_ratio_name" : " 2.35:1",
				"status" : 1,
				"time_stamp" : "2006-01-07"
			},
			{
				"movie_id" : 40,
				"poster": "https://amc-theatres-res.cloudinary.com/v1584531906/amc-cdn/production/2/movies/36500/36533/Poster/p_800x1200_AMC_RiseofthePlanetoftheApes_03152020.jpg",
				"title" : "Rise of the Planet of the Apes",
				"category_name" : "Science Fiction",
				"edition" : "Special Blu-ray Edition",
				"release_year" : 2011,
				"running_time" : 105,
				"rating_name" : "PG-13",
				"disc_format_name" : "Blu-ray + DVD",
				"number_discs" : 2,
				"viewing_format_name" : "Widescreen",
				"aspect_ratio_name" : " 2.35:1",
				"status" : 1,
				"time_stamp" : "2011-12-22"
			},
			{
				"movie_id" : 41,
				"title" : "Robocop",
				"poster": "http://www.robocop.com.br/wp-content/uploads/photo-gallery/242138447c2abd6557f8ec9c293d0825.jpg",
				"category_name" : "Science Fiction",
				"edition" : "",
				"release_year" : 1987,
				"running_time" : 103,
				"rating_name" : "R",
				"disc_format_name" : "DVD",
				"number_discs" : 1,
				"viewing_format_name" : "Widescreen",
				"aspect_ratio_name" : " 1.85:1",
				"status" : 1,
				"time_stamp" : "2006-08-31"
			},
			{
				"movie_id" : 42,
				"title" : "Starship Troopers",
				"poster": "https://i.pinimg.com/originals/41/35/76/4135767c472f6c489333dff69f112a0c.jpg",
				"category_name" : "Science Fiction",
				"edition" : "",
				"release_year" : 1997,
				"running_time" : 130,
				"rating_name" : "R",
				"disc_format_name" : "DVD",
				"number_discs" : 1,
				"viewing_format_name" : "Widescreen",
				"aspect_ratio_name" : " 1.78:1",
				"status" : 1,
				"time_stamp" : "2006-01-07"
			},
			{
				"movie_id" : 43,
				"title" : "The Terminator",
				"poster": "https://www.themoviedb.org/t/p/original/omeCJtJMaXWk2wiMndLSuVs1zSf.jpg",
				"category_name" : "Science Fiction",
				"edition" : "",
				"release_year" : 1984,
				"running_time" : 107,
				"rating_name" : "R",
				"disc_format_name" : "Blu-ray",
				"number_discs" : 1,
				"viewing_format_name" : "Widescreen",
				"aspect_ratio_name" : " 2.78:1",
				"status" : 1,
				"time_stamp" : "2012-10-25"
			},
			{
				"movie_id" : 44,
				"title" : "Terminator 2: Judgment Day",
				"poster": "https://www.cinemaclock.com/images/posters/1000x1500/22/terminator-2-judgment-day-1991-us-poster.jpg",
				"category_name" : "Science Fiction",
				"edition" : "Skynet Edition",
				"release_year" : 1991,
				"running_time" : 152,
				"rating_name" : "R",
				"disc_format_name" : "Blu-ray",
				"number_discs" : 1,
				"viewing_format_name" : "Widescreen",
				"aspect_ratio_name" : " 2.78:1",
				"status" : 1,
				"time_stamp" : "2012-10-25"
			},
			{
				"movie_id" : 45,
				"title" : "Total Recall",
				"poster": "https://i.pinimg.com/originals/5c/af/8a/5caf8aa9c4eb65cdaded4057452723df.jpg",
				"category_name" : "Science Fiction",
				"edition" : "",
				"release_year" : 1990,
				"running_time" : 113,
				"rating_name" : "R",
				"disc_format_name" : "Blu-ray",
				"number_discs" : 1,
				"viewing_format_name" : "Widescreen",
				"aspect_ratio_name" : " 2.78:1",
				"status" : 1,
				"time_stamp" : "2012-08-31"
			},	
			{
				"movie_id" : 46,
				"title" : "War of the Worlds",
				"poster": "https://image.tmdb.org/t/p/original/zscpx0An45zZKYVNnzCRkHuBfQt.jpg",
				"category_name" : "Science Fiction",
				"edition" : "Widescreen Edition",
				"release_year" : 2005,
				"running_time" : 117,
				"rating_name" : "PG-13",
				"disc_format_name" : "DVD",
				"number_discs" : 1,
				"viewing_format_name" : "Widescreen",
				"aspect_ratio_name" : " 1.85:1",
				"status" : 1,
				"time_stamp" : "2011-10-30"
			},
			{
				"movie_id" : 47,
				"title" : "Watchmen",
				"poster": "https://i.pinimg.com/originals/e9/92/57/e99257f4a81ef1f642068649db777655.jpg",
				"category_name" : "Action",
				"edition" : "Widescreen Edition",
				"release_year" : 2009,
				"running_time" : 186,
				"rating_name" : "R",
				"disc_format_name" : "Blu-ray",
				"number_discs" : 2,
				"viewing_format_name" : "Widescreen",
				"aspect_ratio_name" : " 1.85:1",
				"status" : 1,
				"time_stamp" : "2011-10-30"
			},
			{
					"movie_id" : 48,
					"title" : "Fast and the Furious",
					"poster": "https://image.tmdb.org/t/p/original/3xdMcwj0uinmyt01qXg4DhQAbrY.jpg",
					"theatrical_release_order" : 1,
					"true_chronological_order" : 1,
					"category_name" : "Action",
					"release_year" : 2001,
					"running_time" : 107,
					"rating_name" : "PG-13",
					"disc_format_name" : "Blu-ray",
					"number_discs" : 1,
					"viewing_format_name" : "Widescreen",
					"aspect_ratio_name" : " 2.35:1",
					"status" : 1,
					"time_stamp" : "2015-02-22"
			},
			{
			"movie_id" : 49,
					"title" : "2 Fast 2 Furious",
					"poster": "https://image.tmdb.org/t/p/original/7UoWBDRQ3lMBfuxezFLUyo7wgFa.jpg",
					"theatrical_release_order" : 2,
					"true_chronological_order" : 2,
					"category_name" : "Action",
					"release_year" : 2003,
					"running_time" : 108,
					"rating_name" : "PG-13",
					"disc_format_name" : "Blu-ray",
					"number_discs" : 1,
					"viewing_format_name" : "Widescreen",
					"aspect_ratio_name" : " 2.35:1",
					"status" : 1,
					"time_stamp" : "2015-02-22"
				},
				{
				"movie_id" : 50,
					"title" : "Fast and the Furious: Tokyo Drift",
					"poster": "https://image.tmdb.org/t/p/original/g5pxxYlRJU7bG6ijgDbewXonmSY.jpg",
					"theatrical_release_order" : 3,
					"true_chronological_order" : 6,
					"category_name" : "Action",
					"release_year" : 2006,
					"running_time" : 105,
					"rating_name" : "PG-13",
					"disc_format_name" : "Blu-ray",
					"number_discs" : 1,
					"viewing_format_name" : "Widescreen",
					"aspect_ratio_name" : " 2.35:1",
					"status" : 1,
					"time_stamp" : "2015-02-22"
				  },
				{
				  "movie_id" : 51,
					"title" : "Fast & Furious 4",
					"poster": "https://lh3.googleusercontent.com/-n1C1mfsxh9I/XCIrP68KGxI/AAAAAAAABkQ/Gk2fno3niv4ee_4M05VsRwYHqnH85gqmQCHMYCw/s1600/IMG_20181225_181443_899.jpg",
					"theatrical_release_order" : 4,
					"true_chronological_order" : 3,
					"category_name" : "Action",
					"release_year" : 2009,
					"running_time" : 107,
					"rating_name" : "PG-13",
					"disc_format_name" : "Blu-ray",
					"number_discs" : 1,
					"viewing_format_name" : "Widescreen",
					"aspect_ratio_name" : " 2.35:1",
					"status" : 1,
					"time_stamp" : "2015-02-22"
				},
				{
				"movie_id" : 52,
					"title" : "Fast Five",
					"poster": "https://i.pinimg.com/originals/84/db/40/84db40d1b5eb33dccdb25cde5765b30a.jpg",
					"theatrical_release_order" : 5,
					"true_chronological_order" : 4,
					"category_name" : "Action",
					"release_year" : 2011,
					"running_time" : 132,
					"rating_name" : "PG-13",
					"disc_format_name" : "Blu-ray + DVD",
					"number_discs" : 2,
					"viewing_format_name" : "Widescreen",
					"aspect_ratio_name" : " 2.35:1",
					"status" : 1,
					"time_stamp" : "2011-10-30"
				},
				{
				"movie_id" : 53,
					"title" : "Fast & Furious 6",
					"poster": "https://www.themoviedb.org/t/p/original/5SNiGClCzULJKiEHjodzE5aVzBu.jpg",
					"theatrical_release_order" : 6,
					"true_chronological_order" : 5,
					"category_name" : "Action",
					"release_year" : 2013,
					"running_time" : 131,
					"rating_name" : "PG-13",
					"disc_format_name" : "Blu-ray + DVD",
					"number_discs" : 2,
					"viewing_format_name" : "Widescreen",
					"aspect_ratio_name" : " 2.35:1",
					"status" : 1,
					"time_stamp" : "2014-01-03"
				},
				{
				"movie_id" : 54,
					"title" : "Furious 7",
					"poster": "https://picfiles.alphacoders.com/354/thumb-1920-354258.jpg",
					"theatrical_release_order" : 7,
					"true_chronological_order" : 7,
					"category_name" : "Action",
					"release_year" : 2015,
					"running_time" : 131,
					"rating_name" : "PG-13",
					"disc_format_name" : "Blu-ray + DVD",
					"number_discs" : 2,
					"viewing_format_name" : "Widescreen",
					"aspect_ratio_name" : " 2.35:1",
					"status" : 1,
					"time_stamp" : "2014-01-03"
				},
				{
				"movie_id" : 55,
					"title" : "Fast 8",
					"poster": "https://4.bp.blogspot.com/-BL2wvyhCDVE/WL66JiajnKI/AAAAAAAAY3M/3PuH3_n47YkfhFQUgOkQA5U4JVy9LBMBQCLcB/s1600/LOCALIZED_FAST_8_INT_PAYOFF_SHT_OV.jpg",
					"theatrical_release_order" : 8,
					"true_chronological_order" : 8,
					"category_name" : "Action",
					"release_year" : 2017,
					"running_time" : 0,
					"rating_name" : "",
					"disc_format_name" : "",
					"number_discs" : 0,
					"viewing_format_name" : "Widescreen",
					"aspect_ratio_name" : " ",
					"status" : 0,
					"time_stamp" : ""
				}

]